name: tasktrack
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0  # SQLite for database management (null-safe version)
  path_provider: ^2.1.5  # To get the correct path for storing the SQLite file
  flutter_spinkit: ^5.1.0  # Spinner animations (check if null-safe)
  cupertino_icons: ^1.0.0  # Cupertino icons for iOS-like design
  carousel_slider: ^4.0.0  # For carousel widget (null-safe version)
  flutter_local_notifications: ^17.2.4 # For local notifications
  provider: ^6.1.2  # For state management, if needed in the future (useful for managing dark mode state)
  permission_handler: ^10.2.0
  pdf: ^3.6.0
  printing: ^5.5.0
  timezone: ^0.9.4
  percent_indicator: ^4.0.0
  fl_chart: ^0.35.0
  font_awesome_flutter: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/icon.png
